* geometric metafors
imagine if you will a metafor of sorts.

a man drives in a very expensive humwee across the american midwest.
the driver, a producer of intense industrial techno, a niche but oddly
lucrative subgenre, worn out from decades of substance abuse, gets
lost and asks the way from a farmer, conveniently placed in the middle
of these enormouse plains. the driver asks the way. the farmer gently
explains there is no way to go to point c from here. from a to b is
fine, point c is not possible.  geometry dissallows it. angered, the
driver plows full steam ahead, only to discover the farmer was
correct.

imagine if you will another metafor of sorts.

there is a man in our
midst, hes slightly better than us. earns slightly better, has a
slightly more happy life in summary. he explains to us hes the judas
man, in analogue with the judas goat that leads his herd to the
slaughter. he is blessed in this way by our secret overlords, that
feast on the lives we live, but sometimes we need a little bit of
encouragement from our peers, to get the taste just right.
judas man explains theres erally no way out. you can try all you want
to escape the fold, with rebellious tatoos, punk hairdo, breaking taboos, or other ways to be
special. all you can  ever come up with is within the well known limits and
acceptable parameter variations. judas man fills no purpose, but he
doesnt mind.

theres simply no fucking around with the laws of geometry.


final metafor: imagine im a guru, a priest, an autocratic
businessman. im a path to your god. i offer a way out, via the
infinite which suffers not from the stiffling boundaries of
geometry. I am to you what a sphere is to a square. you live in the
flatlands, and I in the higher dimensions. Or, thats what I give the
appearance of. Perhaps there is a way out, but do you really need me
to help you find out?
