(defun make-pdf ()
  (interactive)
  (customize-set-variable 'org-export-with-sub-superscripts nil)
  (customize-set-variable 'org-export-with-emphasize nil)
  (find-file "/data/fanzine.org")
;(find-file "fanzine.org")
  (set-buffer "fanzine.org")
  (add-to-list 'org-latex-default-packages-alist "\\PassOptionsToPackage{hyphens}{url}")
  (customize-set-value 'org-latex-hyperref-template "\\hypersetup{\n pdfauthor={%a},\n pdftitle={%t},\n pdfkeywords={%k}, pdfsubject={%d},\n pdfcreator={%c},\n pdflang={%L},\n colorlinks=true,urlcolor=blue,linkcolor=blue}\n")
 ;(let ((default-directory "~/proj/geometry-lost-fanzine/output"))
 ;  (org-latex-export-to-pdf))
  (cd "/outputdir")
  (org-latex-export-to-pdf))


;;(ignore-errors (or (make-pdf) t))
 (make-pdf)

(switch-to-buffer "*Org PDF LaTeX Output*")
;(write-file "output/org-pdf-latex-output.txt" nil)
(write-file "/outputdir/org-pdf-latex-output.txt" nil)
