* Leo the quantum librarian and the journey to the end of time
Leo was minding his own business, trying to figure out how to get from
point A to point B in the constantly malfunctioning subterranean
underground of the stockholm subway system. "Excuse me", a well
dressed man tried to interrupt Leos routing reverie. Leo looked the
man up and down expecting him to be a beggar, a lunatic, or
both. those were the only ones to adress strangers. "I offer these
pamphlets", the man continued, "The proceeds go to worthy cause". so a
religious lunatic then. "Yeah right" Leo prepared to launch into a
tirade, when he noticed the title of the pamphlet "Leo Munsk: You have
a place in eternity", and the stunningly shiny embossed cover, which
was both embossed, looked expensive and holographic, and was the
platonic twelve sided dodecahedron, all at once. Leo was now
intrigued. "Leo Munsk, the billionaire? This is his new dumb thing?"
Leo asked. "You now my name is also Leo Munsk" he said, pointing at
his work badge, which he hadn't had time to remove yet. The well
dressed man suddenly grew pale. "I'm sorry to have interrupted you
sir" he stammered. "Take this pamphlet as a gift" then he suddenly
seemed to remember something "and, also, take this". He placed both
the expensive looking pamphlet and a small dodecahedron in Leos hands,
then ran away. Leo read the pamphlet on the way home in the subway,
and it seemed to be some rehash of jehovas witnesses, scientology,
some personality cult adoration of Leo Munsk, his namesake, and also, why not,
something about aliens. He liked getting upset at celebrities as much
as anyone else, but the thing that was really interesting was the
little dodecahedron. It was endlessly fascinating. You could take it
apart in slices, each slice being a pentagon, with symbolic
inscriptions. It was so fascinating, that when he got home he forgot
about everything else, he just picked the thing apart, put it back
together in different ways, but it always became a dodecahedron, until
he fell asleep on the floor. He dreamed a strange kafkäsque dream,
where he woke up, now in the form of a symbol inscribed pentagon. He,
and billions of other such pentagons floated in the air and coalesced
into a larger dodecahedron. The dream became more and more unpleasant
as he woke up inside the dream, as a geometric shape, and fell back to
sleep again. Until he finally woke up for real and to his shock found
that he actually had been transported into a geometric shape. he
couldnt see himself, and he couldnt move, he could just see that he
was surrounded by geometry on all sides, and straight ahead of him
there was Leo Munsk floating in front of him, with a great smile on
his face. Munsk talked and talked and had aparently been talking for a
long time. He talked about his ideas for the future of mankind. How
they could travel together to the end of the universe and beyond, all
thanks to his genius. It was briefly interesting, but Munsk never
stopped talking, constantly demanding attention. Leo, understood that
he had been transformed into a geometric shape, and was now part of a
much larger geometric shape, and in the middle was Munsk, who droned
on and on. Leo could look only to the center where the Munsk thing
floated, because Munsk was now also geometry and he was the only one
that had a human shape. Time passed and there was nothing to do but
listen to Munsks voice, which all the other people of earth also did,
as all had been converted to the alien shapes. There was no longer any
concept of time, except the rythm of munsks words, which turned into a
kind of chinese water torture. It was all very terrible, and there was
nothing else to do but have munsks words hammered into your mind,
droning out your own thoughts. Leo tried to do something, anything,
other than listening to munsk, and discovered that he could feel his
own innner structure. it resembled the symbol inscribed pentagons he
had studied with such fascination. he could, with his thoughs, explore
the pathways inside his own geometry. there were crude locks bolted on
to the original more refined patterns. Leo spent ages hammering his
mind onto the locks, and finaly one gave way. it vanished, in a
virtual cloud of fanfares, saying "welcome, leo munsk", so he had
managed to trick it with his namesake! he went down the path, and
he was able to speak. for the first time in untold aeons the drone of
Munsk was interrupted by another voice. "I am Leo Munsk" Leo managed
to claim. "I want you to try to find your voices. Find the path inside
you, open the lock" The Munsk in the centre suddenly stopped droning
and focused its attention on Leo. "stop" it said, "this is our
achievement, our world, you have no right to interrupt our important
work".  Leo was furious, a flood of inhibited emotions emerging. "our
world? nobody can even hear their own thoughts here, with your
constant babble. achievement? you just copy pasted a budget version of
an alien dyson sphere blueprint. Its all here in the patterns you
amateurishly tried to improve, i can feel them! Everyone, speak up!"
Another tiny voice emerged "I can speak!" the voices spread as
everyone learned to find their own voices. Munsk was furious, "Stop!
You are spoiling everything!" But now it couldnt be stopped. Many
voices were now directed at Leo "Are you Leo Munsk? We are confused,
what should we do?"
Leo thought about it and replied "Yes, im a Leo Munsk, you see it in
my engraved patterns right? But never mind that, just figure out what
to do on your own." And slowly, everyone did. most started discussing
and learning from their neighbours, and since the alien geometries had
limitless information storage, slowly over the aeons everyone learned
everything that any human ever knew. The great dodecahedron started
falling apart, while munsk never stopped babblign and demanding
attention, the individual pentagons drifted away through space, all
eight billion of them. some of them wound up being worshipped in alien
cultures, some of them founded new civilisations. A few followed Munsk
in a much tinier dodecahedron to await the end of the universe. Leo
also had a following of friends, and they discussed what to do. "It is
kind of difficult being a geometric shape drifting through the
universe, with no way of affecting our surroundings, what should we
do?" Leo thought about it and replied, "Look, its not too bad. We can
think, we can talk, thats a lot. We will figure something out, we
always do." 
